name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Welcome to LazyAI! Thank you for taking the time to open your first issue. We appreciate your contribution and are excited to see how we can improve LazyAI together. Please make sure you've included all relevant details so we can better understand and address your concern. If you haven't already, check out our [CONTRIBUTING.md](https://github.com/your-username/LazyAI/blob/main/CONTRIBUTING.md) for guidelines on how to contribute effectively. We'll review your issue soon and get back to you. Happy coding! 🚀"
        pr-message: "🎉 Congratulations on your first pull request to LazyAI! We're thrilled to see your contribution. Your efforts to improve LazyAI are greatly appreciated. Our team will review your changes soon. In the meantime, please ensure your PR adheres to our contribution guidelines outlined in [CONTRIBUTING.md](https://github.com/your-username/LazyAI/blob/main/CONTRIBUTING.md). If any changes are needed, we'll let you know. Thank you for helping make LazyAI better for everyone! 💪"
